### PR TITLE
Cast audience to string because of possible lazily evaluated variables.

### PR DESCRIPTION
**Pull request by jotes**
Hi @Osmose,

Could you share your thoughts/review this?

Thanks in advance.

### CODE REVIEW

**Comment by jotes** [comment]
Our use-case: mozilla/pontoon#446

**Comment by Osmose** [comment]
This looks fine and works, nice job!

However, while I was refreshing my brain to be able to properly review this, I thought of two things:
1. It might be simpler to just make `django_browserid.base.get_audience` handle the lazy value rather than casting everywhere, although it would be less flexible than your current solution, which handles lazy values for custom backends and such better.
2. It might even be simpler to have Pontoon [use a custom auth backend](http://django-browserid.readthedocs.io/en/latest/user/customization.html#customizing-the-authentication-backend) and override `BrowserIDBackend.verify` to cast the audience when you receive it. That'd avoid having to do a release for this library, which I'd like to avoid.

Thoughts?

**Comment by jotes** [comment]
I think the second option would be the best if @mathjazz will approve. I just thought this will be more general case that could be solved in BrowserID-browser.
Again, thx for help!

**Comment by Osmose** [comment]
> I just thought this will be more general case that could be solved in BrowserID-browser.

It is, but given the doom surrounding Persona I'm not really up for general improvements to the library.

DOOM

Thanks again for the PR though!

**Comment by mathjazz** [comment]
> I think the second option would be the best if @mathjazz will approve.

I approve anything that allows us to not release a new version of django-browserid 2 months before Persona is doomed. ;)

**Pull request closed without merging**
